# Generated by Django 3.0.6 on 2020-05-20 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(null=True, upload_to='')),
                ('subjectName', models.CharField(max_length=100, null=True)),
                ('subjectCode', models.CharField(max_length=15, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('examType', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact_no', phone_field.models.PhoneField(blank=True, help_text='contact phone number', max_length=31)),
                ('Class', models.CharField(choices=[('B.Tech-CSE', 'B.Tech-CSE'), ('B.Tech-ECE', 'B.Tech-ECE'), ('B.Tech-ECSE', 'B.Tech-ECSE'), ('M.Tech-CSE', 'M.Tech-CSE'), ('M.Tech-ECE', 'M.Tech-ECE'), ('M.Tech-ECSE', 'M.Tech-ECSE')], max_length=20, null=True)),
                ('semester', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=5, null=True)),
                ('roll_no', models.CharField(max_length=15, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
