# Generated by Django 3.0.6 on 2020-05-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0003_auto_20200520_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaper',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
