# Generated by Django 3.0.6 on 2020-05-21 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0004_auto_20200521_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
