# Generated by Django 3.0.6 on 2020-05-22 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionBank.Student'),
        ),
    ]
