# Generated by Django 3.0.6 on 2020-05-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0007_auto_20200522_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Feedback',
        ),
    ]
