# Generated by Django 3.0.6 on 2020-05-23 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0008_auto_20200522_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaperDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100, null=True)),
                ('subjectCode', models.CharField(max_length=15, null=True)),
                ('year', models.CharField(max_length=4, null=True)),
                ('examType', models.CharField(choices=[('Minor-1', 'Minor-1'), ('Minor-2', 'Minor-2'), ('Major', 'Major')], max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='examType',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='subjectCode',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='subjectName',
        ),
        migrations.RemoveField(
            model_name='questionpaper',
            name='year',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questionBank.QuestionPaperDetail'),
        ),
    ]
