# Generated by Django 3.0.6 on 2020-05-25 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0009_auto_20200523_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaperdetail',
            name='date_created',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
