# Generated by Django 3.0.6 on 2020-05-26 19:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0010_auto_20200525_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionpaper',
            name='date_created',
        ),
        migrations.AddField(
            model_name='questionpaperdetail',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
