# Generated by Django 3.0.6 on 2020-07-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0012_auto_20200703_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaperdetail',
            name='year',
            field=models.IntegerField(choices=[(2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)]),
        ),
    ]
