# Generated by Django 3.0.6 on 2020-07-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0014_auto_20200704_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
