# Generated by Django 3.0.6 on 2020-07-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0015_auto_20200704_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
