# Generated by Django 3.0.6 on 2020-07-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0016_auto_20200726_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Class',
            field=models.CharField(blank=True, choices=[('B.Tech-CSE', 'B.Tech-CSE'), ('B.Tech-ECE', 'B.Tech-ECE'), ('B.Tech-ECSE', 'B.Tech-ECSE'), ('M.Tech-CSE', 'M.Tech-CSE'), ('M.Tech-ECE', 'M.Tech-ECE'), ('M.Tech-ECSE', 'M.Tech-ECSE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], max_length=2),
        ),
    ]
