# Generated by Django 3.0.6 on 2020-07-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0017_auto_20200726_2013'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionpaperdetail',
            unique_together={('subjectName', 'subjectCode')},
        ),
    ]
