# Generated by Django 3.0.6 on 2020-11-08 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0018_auto_20200726_2052'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionpaperdetail',
            unique_together=set(),
        ),
    ]
