# Generated by Django 3.0.6 on 2020-11-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0019_auto_20201108_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
    ]
