# Generated by Django 3.0.6 on 2020-11-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0020_auto_20201122_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
