# Generated by Django 3.0.6 on 2020-11-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionBank', '0021_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
    ]
